### ISSUE TITLE
Subtitles not showing

### ISSUE THREAD

**Issue by gecXMAN** [lowlevel-1989/msubtitles-report#1]
From today subtitles are not showing, they are listed in selection form but they are not displaying on the screen, maybe it's related to today's stremio issues with opensubtitles official addon.

**Comment by lowlevel-1989** [comment]
You need to provide more information for us to assist you effectively, such as the device you're using and some screenshots.

**Comment by lowlevel-1989** [comment]
@gecXMAN Leave me a link to one of your subtitles so I can review it please and if possible your username.

**Comment by gecXMAN** [comment]
gemmali
[https://msubtitles.lowlevel1989.click/dashboard/subtitle/tt9185206/](url)

I'm mainly using android tv but it's not working on PC too,none of the subtitles works anymore from yesterday afternoon, till then everything was working fine and I know two other users that have the same issue.
Subtitles appear on selection screen but when You select them on andorid tv nothing happens, on PC this error appears, my network connection is fine,movie streams without problems:
![msuberror](https://github.com/lowlevel-1989/msubtitles-report/assets/110663604/825cfa55-e5a7-4e98-bbcf-040c6660feee)

**Comment by lowlevel-1989** [comment]
> gemmali [https://msubtitles.lowlevel1989.click/dashboard/subtitle/tt9185206/](url)
> 
> I'm mainly using android tv but it's not working on PC too,none of the subtitles works anymore from yesterday afternoon, till then everything was working fine and I know two other users that have the same issue. Subtitles appear on selection screen but when You select them on andorid tv nothing happens, on PC this error appears, my network connection is fine,movie streams without problems: ![msuberror](https://user-images.githubusercontent.com/110663604/277261059-825cfa55-e5a7-4e98-bbcf-040c6660feee.jpg)


I have been running tests with your subtitle and your account, and I've noticed that the issue arises when the Opensubtitles addon encounters an error while delivering subtitles. Stremio doesn't handle subtitles efficiently if MSubtitles is not installed before Opensubtitles.

Nevertheless, the system is working correctly. I will send you some screenshots of the tests, and you should also receive a notification in your user account with the video hash that I watched with your subtitle.

If you can provide me with more evidence, the version of Stremio you are using, or even details about users experiencing similar issues, it would be greatly appreciated.

You may also consider temporarily uninstalling Opensubtitles for testing purposes, as it appears to be the source of the error shown in the screenshot. 

android tablet
![image](https://github.com/lowlevel-1989/msubtitles-report/assets/8493573/c9b0f06d-83bf-46a7-96e6-ac23e27a8bdd)
![image](https://github.com/lowlevel-1989/msubtitles-report/assets/8493573/4d4f6637-1d27-4f1c-9b94-4b39a5d80d6b)
![image](https://github.com/lowlevel-1989/msubtitles-report/assets/8493573/69ed89c5-dc7c-4c1a-9cb7-274d2a5577cf)
![image](https://github.com/lowlevel-1989/msubtitles-report/assets/8493573/f8b41f79-3673-46b2-96b5-127b2504f9f2)


android tv
![image](https://github.com/lowlevel-1989/msubtitles-report/assets/8493573/5d864ca3-31e2-4ef6-82e9-cef0c844476e)


Thank you very much for your assistance.

**Comment by gecXMAN** [comment]
First of all thank You for Your time and effort to solve this problem,
unfortunately nothing works for me, it's always the same error, I have latest versions on PC, android tv and android mobile and it's not working everywhere, I have installed latest version of MSubtitles too, v0.38.2 an tried to install it before and after Opensubtiles v3 addon, then I uninstalled Opensubtiles v3 and left only MSubtitles addon and nothing helped,always the same error, "Failed loading subtitles".
The same subtitle It's obviosly working for you but for me nada :(

**Comment by lowlevel-1989** [comment]
@gecXMAN If you grant me your authorization, I would gladly track your user in real-time. Could you please let me know at what time would be suitable for you to conduct the tests? This way, I can perform a proper analysis. 

Is this issue specific to this movie, or does it occur with every movie you've tried to watch?

**Comment by gecXMAN** [comment]
The most strange thing is that everything was working fine for me until yesterday afternoon.
Authoization data is:
gemmali
xxxx
Do You need for github project where files are stored too?

**Comment by lowlevel-1989** [comment]
@gecXMAN Please refrain from sharing your data with anyone, including me, as it is unnecessary and can pose significant security risks. If you agree, try watching a few TV series and movies for a brief period, at least 2 minutes, so I can verify subtitle compatibility. Approximately two hours later, I will proceed with user tracking if you grant permission.

**Comment by gecXMAN** [comment]
ok

**Comment by lowlevel-1989** [comment]
@gecXMAN Please check in Stremio if you are using the old domain name for MSubtitles, which can be found at https://addons.lowlevel1989.click, or if you have updated to the new domain name at https://msubtitles.lowlevel1989.click. You can perform this check from the addons section in Stremio. If possible, provide a screenshot that includes something similar to this in Stremio: https://msubtitles.lowlevel1989.click/SECRET/api/v1/manifest.json, making sure to remove any sensitive data."

**Comment by lowlevel-1989** [comment]
@gecXMAN You can obtain the information I need through an addon. Simply select the 'share addon' option and copy the information. This way, we can determine the configured domain.

**Comment by gecXMAN** [comment]
I have updated to the new domain, this is info from addon:
https://app.strem.io/shell-v4.4/#/addons/community/all?addon=https%3A%2F%2Fmsubtitles.lowlevel1989.click%2Fconf%2Fapi%2Fv1%2Fmanifest.json

**Comment by lowlevel-1989** [comment]
@gecXMAN I need you to access your profile in the 'Consumer' option on the sidebar. With your account signed in, click the 'Install' button to configure it with your user, ensuring you have the customized version, as the general version won't take your confirmation into account.

**Comment by gecXMAN** [comment]
That's it, it's working now, well done maestro, thank You for your time and patience once again.

**Comment by lowlevel-1989** [comment]
@gecXMAN Thanks to you, I now know that I should change the button names. Regards.
