### ISSUE TITLE
Filename: Only support srt format.

### ISSUE THREAD

**Issue by 9jfcc** [lowlevel-1989/msubtitles-report#10]
Hello, I have tried more than one srt file, but I get this. Is there a solution?

![لقطة شاشة 2024-07-06 205916](https://github.com/lowlevel-1989/msubtitles-report/assets/174891369/8b65e2fe-1186-47e3-a23b-a853d13c213a)

**Comment by lowlevel-1989** [comment]
Yes, To upload simultaneous subtitles, you just need to load a YAML file into the 'url resource' field, as shown in the following example: [Link to the YAML example file](https://github.com/lowlevel-1989/subs/blob/master/demo/friends.yaml)

**Comment by 9jfcc** [comment]
> Yes, To upload simultaneous subtitles, you just need to load a YAML file into the 'url resource' field, as shown in the following example: [Link to the YAML example file](https://github.com/lowlevel-1989/subs/blob/master/demo/friends.yaml)

I did not understand. I am new to github and my English is not good. But if you have time, can you make a picture like this because the pictures are easy to understand manual

**Comment by lowlevel-1989** [comment]
> > Yes, To upload simultaneous subtitles, you just need to load a YAML file into the 'url resource' field, as shown in the following example: [Link to the YAML example file](https://github.com/lowlevel-1989/subs/blob/master/demo/friends.yaml)
> 
> I did not understand. I am new to github and my English is not good. But if you have time, can you make a picture like this because the pictures are easy to understand 

you just need a yaml file with this structure https://github.com/lowlevel-1989/subs/blob/master/demo/friends.yaml and the data source is the following https://github.com/lowlevel-1989/subs/tree/master/friends/1994/.

Spanish example: https://github.com/lowlevel-1989/msubtitles-report/issues/4#issuecomment-1933677012
