### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by vlax74** [lowlevel-1989/msubtitles-report#3]
Is it possible to upload subtitles for entire seasons of series at once or must one subtitle at a time?

**Comment by lowlevel-1989** [comment]
@vlax74.

At the moment, this is not possible, but I will definitely consider it for future versions. Thank you very much for your input.

**Comment by vlax74** [comment]
Tnx!

**Comment by lowlevel-1989** [comment]
> Tnx!

The version that allows simultaneous subtitle loading is now available.

To upload simultaneous subtitles, simply upload a YAML file in the 'url resource' field, as illustrated in the following example: [Link to YAML example file](https://github.com/lowlevel-1989/subs/blob/master/demo/friends.yaml).

**Comment by vlax74** [comment]
Tnx
