### ISSUE TITLE
Having issues trying to upload a YAML file for an anime

### ISSUE THREAD

**Issue by Ilikecofe** [lowlevel-1989/msubtitles-report#4]
Alright I'm trying to upload a batch of sub files for an anime but I'm having some issues

This is my yaml link
https://raw.githubusercontent.com/Ilikecofe/letstrymsub/main/ani/snk/0401/SNKFSpart1.yaml
(not sure if leaving this as "season 1" is correct since it's actually season 4 but it has a kitsu id so that confuses me a bit)

And this is my entry when filling the form
![imagen](https://github.com/lowlevel-1989/msubtitles-report/assets/159062409/cd2ac45a-07a6-4a99-b099-dea23f9cee43)
(in this part should I leave the episode as "0"?)

At first I got an error saying "only srt files are supported" then I tried again and I got the following message
![imagen](https://github.com/lowlevel-1989/msubtitles-report/assets/159062409/7c34a497-c794-474e-b80f-9d2edcfe3b4e)
("you are currently processing a yaml that has not yet been finalized")

Thanks in advance

**Comment by lowlevel-1989** [comment]
> Alright I'm trying to upload a batch of sub files for an anime but I'm having some issues
> 
> This is my yaml link https://raw.githubusercontent.com/Ilikecofe/letstrymsub/main/ani/snk/0401/SNKFSpart1.yaml (not sure if leaving this as "season 1" is correct since it's actually season 4 but it has a kitsu id so that confuses me a bit)
> 
> And this is my entry when filling the form ![imagen](https://private-user-images.githubusercontent.com/159062409/302839286-cd2ac45a-07a6-4a99-b099-dea23f9cee43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTQzNDEsIm5iZiI6MTcwNzI5NDA0MSwicGF0aCI6Ii8xNTkwNjI0MDkvMzAyODM5Mjg2LWNkMmFjNDVhLTA3YTYtNGE5OS1iMDk5LWRlYTIzZjljZWU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwODIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTZjMDc3NWVmYTI1NWE2OWFkYWQzZTM0M2Q5OTE1ZGFiZGM3NmRjNDE1ZGY3OTE5Yjg5YTYzNDY3N2YzM2YzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8TD8pRQ_ElD_th9Ww-0eO_y3B8hHu7uw_fAStDE8_8E) (in this part should I leave the episode as "0"?)
> 
> At first I got an error saying "only srt files are supported" then I tried again and I got the following message ![imagen](https://private-user-images.githubusercontent.com/159062409/302839823-7c34a497-c794-474e-b80f-9d2edcfe3b4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyOTQzNDEsIm5iZiI6MTcwNzI5NDA0MSwicGF0aCI6Ii8xNTkwNjI0MDkvMzAyODM5ODIzLTdjMzRhNDk3LWM3OTQtNDc0ZS1iODBmLTlkMmVkY2ZlM2I0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QwODIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzljYjI4NzNiNDQxMGNhOGM1NTAwZWYyZDQ1MzAyOTQ2ZTExMzRkNjMxOTAxM2ZhZjE5MjJmNWIzYmU2Yzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5_fIbzMVpw0R5mKuCZwpdRZLxR7876G0Ay9X0chuVpo) ("you are currently processing a yaml that has not yet been finalized")
> 
> Thanks in advance

Si, solo esta permitido subir un yaml al tiempo, este se procesa en background, apenas termina de cargar tu subtitulos te permitira cargar mas yaml. (por este caso, he reiniciado todas las solicitudes para que puedas probar de nuevo)

En cuanto al episodio lo tomara del yaml, asi que puedes dejarlo en 0.

El season, debe ser el kitsu id cuando se habla de anime, asegurate que en stremio estes iniciado sesión en el plugin, para que puedas ver el id correcto desde el dashboard de msubtitles.


debes ver un mensaje parecido a este, en tu plugin:
![image](https://github.com/lowlevel-1989/msubtitles-report/assets/8493573/1b65997b-7fe4-4ff2-95e9-fb7c730c677d)


Sobre el otro punto, si abres la serie en stremio y regresas al dashboard de msubtitles te dira el id de kitsu como una notificación.

Para finalizar y verificar que esta pasando con tu usuario y el porque no puedes cargar archivos, lo mejor es que me digas tu usuario y lo valido, el usuario no la clave.

**Comment by Ilikecofe** [comment]
De acuerdo mi usuario en MSubtitles es lakefi123. Debo confirmar que subiendo un subtitulo SRT singular me permite visualizarlo sin problemas en stremio en el episodio correcto y luego de ver en el dashboard pude comprobar que sí estaba usando el kitsu id correcto (yo estaba usando otro método para conseguir este id pero de esta forma parece más directo).

Por cierto es normal que se muestre en stremio el subtitulo con el siguiente nombre?
![imagen](https://github.com/lowlevel-1989/msubtitles-report/assets/159062409/9c1724b1-406d-48ee-849a-5db09310982d)

Sobre el link yaml, ya me permitió subirlo sin problemas, y ahora me doy cuenta de que también debí poner el kitsu-id dentro del archivo yaml (lo habia dejado en season 1). Ahora lo corrijo.

**Comment by Ilikecofe** [comment]
Luego de corregir mi archivo yaml ya aparecen todos los subtitulos en mi dashboard. Pero ahora parece que hay un problema en el apartado de "imdb", cuando subo un archivo srt singular aparece en la pestaña imdb "kitsu-{kitsuid}" (en la imagen de abajo es kitsu-44240) pero cuando subo varios a través de yaml aparece en la pestaña imdb como "kitsu" solamente y no sé si esto esté causando que no aparezcan en stremio. Adjunto screenshot 

![imagen](https://github.com/lowlevel-1989/msubtitles-report/assets/159062409/457728c4-3681-453e-b222-bbe611d03eaf)
El último en la lista fue el que subí como srt, y los primeros son los subidos por yaml
El archivo subido como srt sí aparece en stremio pero los otros subidos por yaml no.

**Comment by lowlevel-1989** [comment]
> lakefi123

Ya te deberia estar funcionando en la version 0.43.5.9, he eliminado los subtitulos para que puedas probar de nuevo, muchas gracias por la ayuda, y ya deberias poder subirlo sin problema, los pasos son los siguiente:

**imdb**: kitsu
**season**: 42422
**url**: [https://raw.githubusercontent.com/Ilikecofe/letstrymsub/main/ani/snk/0401/SNKFSpart1.yaml](https://raw.githubusercontent.com/Ilikecofe/letstrymsub/main/ani/snk/0401/SNKFSpart1.yaml
)

Si todo te funciona correctamente, me lo notificas para poder cerrar el ticket, muchas gracias.

Si me das permiso, utilizo tu yaml para referenciarlo en la actualización de la documentación, ya que no esta facil de seguir la documentación para anime y tenia este bug.

**Comment by lowlevel-1989** [comment]
> De acuerdo mi usuario en MSubtitles es lakefi123. Debo confirmar que subiendo un subtitulo SRT singular me permite visualizarlo sin problemas en stremio en el episodio correcto y luego de ver en el dashboard pude comprobar que sí estaba usando el kitsu id correcto (yo estaba usando otro método para conseguir este id pero de esta forma parece más directo).
> 
> Por cierto es normal que se muestre en stremio el subtitulo con el siguiente nombre? ![imagen](https://private-user-images.githubusercontent.com/159062409/303188703-9c1724b1-406d-48ee-849a-5db09310982d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczODU2NzYsIm5iZiI6MTcwNzM4NTM3NiwicGF0aCI6Ii8xNTkwNjI0MDkvMzAzMTg4NzAzLTljMTcyNGIxLTQwNmQtNDhlZS04NDlhLTVkYjA5MzEwOTgyZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQwOTQyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDIzYzdiOTc0NTI2NDhiY2FmNWZjMGYxZDNmNTI4ZmY5ZWJmODJlNjI0NjhlODg5ZTEzZjZlZjdlMjRiZGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kqhBjJHTHu0Y-_scH7iu2vZcewWh6T1XcIpMHJ1Q3d4)
> 
> Sobre el link yaml, ya me permitió subirlo sin problemas, y ahora me doy cuenta de que también debí poner el kitsu-id dentro del archivo yaml (lo habia dejado en season 1). Ahora lo corrijo.

Si el nombre es el correcto, sigue la siguiente estructura: {**lang**}:{**follow**:03d}:{**username**} [{**hash**}].

Asi como puedes ver el kitsu id, tambien puedes ver el hash del torrent, lo que te permite asignar tu subtitulo a un torrent en especifico y no a todos, esto viene bien en algunos casos cuando solo funciona el subtitulo en algunos torrents.

Se ve cortado porque stremio lo muestra asi, depende del dispositivo te mostrara mas o menos contenido, pero esa estructura permite organizar todos los subtitulos por idioma.

**Comment by Ilikecofe** [comment]
Luego de intentarlo ya puedo confirmar que está funcionando todo correctamente, ya aparecen los subs con "kitsu-42422" y se muestran en stremio correctamente. Agradezco tu apoyo y mencionar lo bueno que es este addon.

Sobre mi archivo yaml, si lo utilizas como referencia ya no podré modificarlo? No tengo problemas si lo llegas a modificar o copiar a tu mismo repositorio.

Una última pregunta, sobre el hash entiendo como implementarlo (en la demo de friends.yaml aparece un ejemplo) y tendría que hacerlo con cada episodio. Mi pregunta es si hay alguna manera más rápida de poder sacar los hash de los episodios de toda una temporada o si solo es posible reproduciendo brevemente cada uno.

**Comment by lowlevel-1989** [comment]
@Ilikecofe si puedes hacer lo que quieras con el, el link no cambia aunque lo modifiques .

sobre el hash no tiene manera sencilla de hacerlo, lo mas sencillo es dejarlo en blanco.
