### ISSUE TITLE
My service is not working

### ISSUE THREAD

**Issue by FredMohbz** [lowlevel-1989/msubtitles-report#5]
I was watching stremio when the subtitles tells me that my quota has ended e guide me to the website, where I follow the steps to increase my quota e it's just don't work for me, I've tried many times and nothing. I've followed step-by-step, I'm pretty sure that I have made exactly what was oriented on the website. 

I've clicked on "install configuration from the app" button and I was redirected for stremio app and that was the message that appears to me:

**Comment by lowlevel-1989** [comment]
> I was watching stremio when the subtitles tells me that my quota has ended e guide me to the website, where I follow the steps to increase my quota e it's just don't work for me, I've tried many times and nothing. I've followed step-by-step, I'm pretty sure that I have made exactly what was oriented on the website.
> 
> I've clicked on "install configuration from the app" button and I was redirected for stremio app and that was the message that appears to me:

Please avoid sharing your private user code. For this reason, I have removed your screenshots. Additionally, could you ensure that you have installed 'msubtitles' only once and that it is the version corresponding to your user? I will be monitoring your user account in this regard. I look forward to your response. Regards.

**Comment by FredMohbz** [comment]
Well, I installed the just one version, the version from the link in the website and I uninstalled e reinstalled to certify and it still don't work, I don't know what to do beyond that ;/

**Comment by lowlevel-1989** [comment]
> Well, I installed the just one version, the version from the link in the website and I uninstalled e reinstalled to certify and it still don't work, I don't know what to do beyond that ;/

I have generated a new user code for you. You will need to log in again and reinstall the addon. This will give you your new code since it seems that your user has not contributed subtitles.

Follow the steps, and I'll be monitoring.


------------------------------------------------------------------------------------------------------------------------------------
limits:
- Unregistered users: You can download a maximum of 2 subtitles per day.
- Registered users without subtitle contributions: You can download a maximum of 4 subtitles per day.
- Registered users (public) with subtitle contributions: You can download a maximum of 10 subtitles per day.

**Comment by zhengyuyu** [comment]
I'm encountering the same problem of reaching the quota limit. I attempted to "install configuration from the app", but it didn't resolve the issue. 
Do the following limits still apply after "install configuration from the app"?

> limits:
> Unregistered users: You can download a maximum of 2 subtitles per day.
> Registered users without subtitle contributions: You can download a maximum of 4 subtitles per day.
> Registered users (public) with subtitle contributions: You can download a maximum of 10 subtitles per day.

**Comment by lowlevel-1989** [comment]
@zhengyuyu hi, you try this ref:  https://github.com/lowlevel-1989/msubtitles-report/issues/1#issuecomment-1775749619

**Comment by mheyermann** [comment]
I am having the same issue. I put my profile public, I updated my profile an then clicked "Install configuration from the app". That shows in Stremio te options to cancel or uninstalled the MSubtitles Addon. Then I clicked Uninstalled and then in my MSubtitle profile I clickd again on "Install configuration from the app". Now on Stremio I have 3 options: cancel, configure or install. I choosed install but I still see the message that my  daily quota has ended. The only difference is that now I have 2 options for the portuguese subts.

Is it because I need a DEEPL API key?

Thanks!

**Comment by lowlevel-1989** [comment]
> I am having the same issue. I put my profile public, I updated my profile an then clicked "Install configuration from the app". That shows in Stremio te options to cancel or uninstalled the MSubtitles Addon. Then I clicked Uninstalled and then in my MSubtitle profile I clickd again on "Install configuration from the app". Now on Stremio I have 3 options: cancel, configure or install. I choosed install but I still see the message that my daily quota has ended. The only difference is that now I have 2 options for the portuguese subts.
> 
> Is it because I need a DEEPL API key?
> 
> Thanks!

No, the service is completely free, follow some of the instructions already explained in this issue and it should solve your problem.

https://github.com/lowlevel-1989/msubtitles-report/issues/5#issuecomment-2063533907

**Comment by luckiluck** [comment]
Hi @lowlevel-1989, if possible, would you consider increasing the daily subtitle quota for users with contributions? The current limit of 10 subtitles per day seems rather low. This is especially true for users like myself who often skim through multiple episodes of a series before deciding to watch it, which can quickly exhaust the daily quota.

**Comment by lowlevel-1989** [comment]
> Hi @lowlevel-1989, if possible, would you consider increasing the daily subtitle quota for users with contributions? The current limit of 10 subtitles per day seems rather low. This is especially true for users like myself who often skim through multiple episodes of a series before deciding to watch it, which can quickly exhaust the daily quota.

Let me know your proposal and I'll reach a compromise for contributors.
For now, registered users can download up to 15 subtitles per day.

~ 15 hours aprox.

**Comment by luckiluck** [comment]
> Let me know your proposal and I'll reach a compromise for contributors. For now, registered users can download up to 15 subtitles per day.

Hi @lowlevel-1989, thank you for your support!
I typically watch an entire series, which often consists of 13-15 episodes, over a weekend. Therefore, a daily limit of 15 subtitles would suffice for my usecase. If possible, it would be even better if you could increase the quota to 20 subtitles per day. 

Alternatively, if possible, I think something like a user ranking system that allows users with better contributions to enjoy a larger quota might help reduce server load and encourage users to contribute more. <---- Just an idea

**Comment by lowlevel-1989** [comment]
> > Let me know your proposal and I'll reach a compromise for contributors. For now, registered users can download up to 15 subtitles per day.
> 
> Hi @lowlevel-1989, thank you for your support!
> I typically watch an entire series, which often consists of 13-15 episodes, over a weekend. Therefore, a daily limit of 15 subtitles would suffice for my usecase. If possible, it would be even better if you could increase the quota to 20 subtitles per day. 
> 
> Alternatively, if possible, I think something like a user ranking system that allows users with better contributions to enjoy a larger quota might help reduce server load and encourage users to contribute more. <---- Just an idea
> 
> 

Yes, I've been working on it. I just need to solve the spam problem and implement automatic analysis of what is uploaded and no longer in the system. This will be part of the 1.1.0.x release.
