### ISSUE TITLE
Problem with subs

### ISSUE THREAD

**Issue by b0ar** [lowlevel-1989/msubtitles-report#6]
Hey, I tried to set up my own subtitles for movie "Priscilla", did everything as in tutorial, but when I tried selecting my new subs in stremio nothing happened, no text appeared. I tried a few times and got a message "You have used up all your daily subtitles. Register [...]". I installed configuration from web while being logged in, but I'm still getting this message. What can I do to set it right?

**Comment by lowlevel-1989** [comment]
> b0ar

Hello, I hope you're doing well. Firstly, I apologize for the issues you're experiencing. Upon reviewing the administrative panel, I've noticed that 'msubtitles' is installed twice on your PC. Please keep only the version associated with your user identification to resolve the problem.

I've attached a screenshot with information about your connections for your reference.

![image](https://github.com/lowlevel-1989/msubtitles-report/assets/8493573/f4067e02-acef-4fa3-a541-a47e48350897)
