### ISSUE TITLE
Cannot add subtitles?

### ISSUE THREAD

**Issue by Maddysub** [lowlevel-1989/msubtitles-report#7]
Hello, I am very new to stremio and this add-on. I have successfully added a subtitles before and it worked perfectly, thanks for your work! but when I tried to added another subtitles (followed the same instruction) for a different movie, this text came up and I simply don't know what I did wrong or what does it mean. Thank you in advance

![Screenshot 2024-04-10 145000](https://github.com/lowlevel-1989/msubtitles-report/assets/166590863/5dfd93d6-2762-4401-9525-6f97c0b90198)

**Comment by lowlevel-1989** [comment]
@Maddysub Hello, I have seen that the problem is presented only by that subtitle, I will need some time to see why it presents that problem, if you try other subtitles you will see that it works without a problem.  I will be working on detecting the error.

**Comment by Maddysub** [comment]
@lowlevel-1989 Hi, Thank you for your respond. I have tried to add another subtitles for a different movie and it still didn't work, I really have no idea what I did wrong or not? I hope you can find the solution soon.

**Comment by lowlevel-1989** [comment]
@Maddysub If you can put the subtitle back in the repository, since I am using it for testing and don't worry, I will try to solve the problem for you as soon as possible

**Comment by Maddysub** [comment]
@lowlevel-1989 I uploaded a couple of the subtitles back in my repository. Thank you.
