### ISSUE TITLE
Account locked

### ISSUE THREAD

**Issue by BeKindRewind1** [lowlevel-1989/msubtitles-report#8]
I accidentally entered in my password wrong and am now locked out of my account. It's telling me to contact admins for my account to be unlocked and I'm not sure who rhe admins are or how to do this!

**Comment by lowlevel-1989** [comment]
> I accidentally entered in my password wrong and am now locked out of my account. It's telling me to contact admins for my account to be unlocked and I'm not sure who rhe admins are or how to do this!

fix this
